### ISSUE TITLE
[BUG] Accounts not saving

### ISSUE THREAD

**Issue by kalmaguer** [MaikEight/ExaltAccountManager#6] opened 2024-05-27 16:15 UTC
**Describe the bug**
When entering my login info the correct username is found, but after clicking "save account" it does not get added and no new row is created. This happens for both email and steam logins.

**Expected behavior**
Account should be added.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Exalt Account Manager Version 4.1.0

**Additional context**
On another windows 10 computer I still have version 4.0.2 installed and it does not have this issue.

**Comment by MaikEight** [comment] 2024-05-27 17:14
Thank you for reporting the issue!
I am already aware of it and am working on a fix. 

Just a question, does the application crash if you open the Logs page or when you change a setting?
If so it most likely has the same root cause, the Database / the DBpool mutex.
As I can't test the fix myself (it works on my machine and on any of the regular testers) it may take a moment longer to fix it.

**Comment by kalmaguer** [comment] 2024-05-27 23:49
Yes, it crashes when I try to open logs, but settings cannot be altered. They stay how they are even when I try to adjust them.

**Comment by MaikEight** [comment] 2024-05-29 00:22
The issue should be fixed with the latest pre-release.
https://github.com/MaikEight/ExaltAccountManager/releases/tag/v4.1.4

**Comment by kalmaguer** [comment] 2024-05-29 02:33
Can confirm, thank you!

**Closed** 2024-05-29 11:25 UTC
Labels: bug
